---

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: true

ingester:
  replicas: 1

distributor:
  replicas: 1

querier:
  replicas: 1

queryFrontend:
  replicas: 1

gateway:
  replicas: 1

compactor:
  replicas: 1
